export default [
  {
    type: 'forms/Button',
    category: 'Forms',
    label: 'Button',
    thumbnail: 'images/widgets/button.png',
  },
  {
    type: 'forms/Checkbox',
    label: 'Checkbox',
    category: 'Forms',
    thumbnail: 'class:la la-check-square-o',
  },
  {
    type: 'forms/ColorPicker',
    label: 'Color Picker',
    category: 'Forms',
    thumbnail: 'class:la la-palette',
  },
  {
    type: 'forms/DatePicker',
    label: 'Date Picker',
    category: 'Forms',
    thumbnail: 'class:la la-calendar',
  },
  {
    type: 'forms/Dropdown',
    label: 'Dropdown',
    category: 'Forms',
    thumbnail: 'images/widgets/combo.png',
  },
  {
    type: 'forms/Heading',
    label: 'Heading',
    category: 'Forms',
    thumbnail: 'class:la la-heading',
  },
  {
    type: 'forms/IconPicker',
    label: 'Icon Picker',
    category: 'Forms',
    thumbnail: 'class:la la-bell',
  },
  {
    type: 'forms/Label',
    label: 'Label',
    category: 'Forms',
    thumbnail: 'images/widgets/label.png',
  },
  {
    type: 'forms/LikeButton',
    label: 'Like Button',
    category: 'Forms',
    thumbnail: 'class: la la-thumbs-up',
  },
  {
    type: 'forms/Link',
    label: 'Link',
    category: 'Forms',
    thumbnail: 'class:la la-external-link-alt',
  },
  {
    type: 'forms/Listbox',
    label: 'ListBox',
    category: 'Forms',
    thumbnail: 'class:la la-list',
  },
  {
    type: 'forms/NumberInput',
    label: 'Number',
    category: 'Forms',
    thumbnail: 'images/widgets/number-entry.png',
  },
  {
    type: 'forms/PasswordInput',
    label: 'Password',
    category: 'Forms',
    thumbnail: 'class:la la-key',
  },
  {
    type: 'forms/SearchEntry',
    label: 'Search Box',
    category: 'Forms',
    thumbnail: 'class:la la-search',
  },
  {
    type: 'forms/TextArea',
    label: 'Multi-line',
    category: 'Forms',
    thumbnail: 'images/widgets/text.png',
  },
  {
    type: 'forms/TextEntry',
    label: 'Text',
    category: 'Forms',
    thumbnail: 'images/widgets/textbox.png',
  },
  {
    type: 'forms/TimePicker',
    label: 'TimePicker',
    category: 'Forms',
    thumbnail: 'class:la la-clock-o',
  },
  {
    type: 'forms/Panel',
    label: 'Panel',
    category: 'Forms',
    thumbnail: 'class: la la-window-maximize',
  },
  {
    type: 'forms/ButtonSwitch',
    label: 'Switch Button',
    category: 'Forms',
    thumbnail: 'class: la la-toggle-on',
  },
  {
    type: 'forms/ProgressBar',
    label: 'Progress Bar',
    category: 'Forms',
    thumbnail: 'images/widgets/progress.png',
  },
  {
    type: 'forms/Slider',
    label: 'Slider',
    category: 'Forms',
    thumbnail: 'class: la la-sliders-h',
  },
  {
    type: 'forms/Image',
    label: 'Image',
    category: 'Forms',
    thumbnail: 'class: la la-image',
  },
  {
    type: 'forms/Paragraph',
    label: 'Paragraph',
    category: 'Forms',
    thumbnail: 'class: la la-paragraph',
  },
];
