export default [
  {
    category: 'General',
    type: 'shapes/box',
    label: 'Box',
    thumbnail: 'images/widgets/box.png',
  },
  {
    category: 'General',
    type: 'shapes/chevron',
    label: 'Chevron',
    thumbnail: 'images/widgets/chevron.png',
  },
  {
    category: 'General',
    type: 'shapes/circle',
    label: 'Circle',
    thumbnail: 'images/widgets/circle.png',
  },
  {
    category: 'General',
    type: 'shapes/database',
    label: 'Database',
    thumbnail: 'images/widgets/database.png',
  },
  {
    category: 'General',
    type: 'shapes/diamond',
    label: 'Diamond',
    thumbnail: 'images/widgets/diamond.png',
  },
  {
    category: 'General',
    type: 'shapes/line_down',
    label: 'Arrow Down',
    thumbnail: 'images/widgets/line_down.png',
  },
  {
    category: 'General',
    type: 'shapes/line_left_angle_bottom',
    label: 'Angle Arrow Left Bottom',
    thumbnail: 'images/widgets/line_angle_left_bottom.png',
  },
  {
    category: 'General',
    type: 'shapes/line_left_angle_down',
    label: 'Angle Arrow Left Down',
    thumbnail: 'images/widgets/line_angle_left_down.png',
  },
  {
    category: 'General',
    type: 'shapes/line_left_angle_up',
    label: 'Angle Arrow Left Up',
    thumbnail: 'images/widgets/line_angle_left_up.png',
  },
  {
    category: 'General',
    type: 'shapes/line_left_top_angle',
    label: 'Angle Arrow Top Left',
    thumbnail: 'images/widgets/line_angle_left_top.png',
  },
  {
    category: 'General',
    type: 'shapes/line_left',
    label: 'Arrow Left',
    thumbnail: 'images/widgets/line_left.png',
  },
  {
    category: 'General',
    type: 'shapes/line_right_angle_bottom',
    label: 'Angle Arrow Right Bottom',
    thumbnail: 'images/widgets/line_angle_right_bottom.png',
  },
  {
    category: 'General',
    type: 'shapes/line_angle_down',
    label: 'Angle Arrow Right Down',
    thumbnail: 'images/widgets/line_angle_right_down.png',
  },
  {
    category: 'General',
    type: 'shapes/line_angle_up',
    label: 'Angle Arrow Right Up',
    thumbnail: 'images/widgets/line_angle_right_up.png',
  },
  {
    category: 'General',
    type: 'shapes/line_right_top_angle',
    label: 'Angle Arrow Top Right',
    thumbnail: 'images/widgets/line_angle_right_top.png',
  },
  {
    category: 'General',
    type: 'shapes/line_right',
    label: 'Arrow Right',
    thumbnail: 'images/widgets/line_right.png',
  },
  {
    category: 'General',
    type: 'shapes/line_up',
    label: 'Arrow Up',
    thumbnail: 'images/widgets/line_up.png',
  },
  {
    category: 'General',
    type: 'shapes/line_zigzag_left',
    label: 'Zig-Zag Left',
    thumbnail: 'images/widgets/line_zigzag_left.png',
  },
  {
    category: 'General',
    type: 'shapes/line_zigzag_right',
    label: 'Zig-Zag Right',
    thumbnail: 'images/widgets/line_zigzag_right.png',
  },
  {
    category: 'General',
    type: 'shapes/parallelogram',
    label: 'Parallelogram',
    thumbnail: 'images/widgets/parallelogram.png',
  },
  {
    category: 'General',
    type: 'shapes/triangle',
    label: 'Triangle',
    thumbnail: 'class:la la-caret-up',
  },
];
