export default {
  "la-500px": "500px",
  "la-adjust": "Adjust",
  "la-adn": "Adn",
  "la-align-center": "Align Center",
  "la-align-justify": "Align Justify",
  "la-align-left": "Align Left",
  "la-align-right": "Align Right",
  "la-amazon": "Amazon",
  "la-ambulance": "Ambulance",
  "la-anchor": "Anchor",
  "la-android": "Android",
  "la-angellist": "Angellist",
  "la-angle-double-down": "Angle Double Down",
  "la-angle-double-left": "Angle Double Left",
  "la-angle-double-right": "Angle Double Right",
  "la-angle-double-up": "Angle Double Up",
  "la-angle-down": "Angle Down",
  "la-angle-left": "Angle Left",
  "la-angle-right": "Angle Right",
  "la-angle-up": "Angle Up",
  "la-apple": "Apple",
  "la-archive": "Archive",
  "la-area-chart": "Area Chart",
  "la-arrow-circle-down": "Arrow Circle Down",
  "la-arrow-circle-left": "Arrow Circle Left",
  "la-arrow-circle-o-down": "Arrow Circle O Down",
  "la-arrow-circle-o-left": "Arrow Circle O Left",
  "la-arrow-circle-o-right": "Arrow Circle O Right",
  "la-arrow-circle-o-up": "Arrow Circle O Up",
  "la-arrow-circle-right": "Arrow Circle Right",
  "la-arrow-circle-up": "Arrow Circle Up",
  "la-arrow-down": "Arrow Down",
  "la-arrow-left": "Arrow Left",
  "la-arrow-right": "Arrow Right",
  "la-arrow-up": "Arrow Up",
  "la-arrows": "Arrows",
  "la-arrows-alt": "Arrows Alt",
  "la-arrows-h": "Arrows H",
  "la-arrows-v": "Arrows V",
  "la-asterisk": "Asterisk",
  "la-at": "At",
  "la-automobile": "Automobile",
  "la-backward": "Backward",
  "la-balance-scale": "Balance Scale",
  "la-ban": "Ban",
  "la-bank": "Bank",
  "la-bar-chart": "Bar Chart",
  "la-bar-chart-o": "Bar Chart O",
  "la-barcode": "Barcode",
  "la-bars": "Bars",
  "la-battery-0": "Battery 0",
  "la-battery-1": "Battery 1",
  "la-battery-2": "Battery 2",
  "la-battery-3": "Battery 3",
  "la-battery-4": "Battery 4",
  "la-battery-empty": "Battery Empty",
  "la-battery-full": "Battery Full",
  "la-battery-half": "Battery Half",
  "la-battery-quarter": "Battery Quarter",
  "la-battery-three-quarters": "Battery Three Quarters",
  "la-bed": "Bed",
  "la-beer": "Beer",
  "la-behance": "Behance",
  "la-behance-square": "Behance Square",
  "la-bell": "Bell",
  "la-bell-o": "Bell O",
  "la-bell-slash": "Bell Slash",
  "la-bell-slash-o": "Bell Slash O",
  "la-bicycle": "Bicycle",
  "la-binoculars": "Binoculars",
  "la-birthday-cake": "Birthday Cake",
  "la-bitbucket": "Bitbucket",
  "la-bitbucket-square": "Bitbucket Square",
  "la-bitcoin": "Bitcoin",
  "la-black-tie": "Black Tie",
  "la-bluetooth": "Bluetooth",
  "la-bluetooth-b": "Bluetooth B",
  "la-bold": "Bold",
  "la-bolt": "Bolt",
  "la-bomb": "Bomb",
  "la-book": "Book",
  "la-bookmark": "Bookmark",
  "la-bookmark-o": "Bookmark O",
  "la-briefcase": "Briefcase",
  "la-btc": "Btc",
  "la-bug": "Bug",
  "la-building": "Building",
  "la-building-o": "Building O",
  "la-bullhorn": "Bullhorn",
  "la-bullseye": "Bullseye",
  "la-bus": "Bus",
  "la-buysellads": "Buysellads",
  "la-cab": "Cab",
  "la-calculator": "Calculator",
  "la-calendar": "Calendar",
  "la-calendar-check-o": "Calendar Check O",
  "la-calendar-minus-o": "Calendar Minus O",
  "la-calendar-o": "Calendar O",
  "la-calendar-plus-o": "Calendar Plus O",
  "la-calendar-times-o": "Calendar Times O",
  "la-camera": "Camera",
  "la-camera-retro": "Camera Retro",
  "la-car": "Car",
  "la-caret-down": "Caret Down",
  "la-caret-left": "Caret Left",
  "la-caret-right": "Caret Right",
  "la-caret-square-o-down": "Caret Square O Down",
  "la-caret-square-o-left": "Caret Square O Left",
  "la-caret-square-o-right": "Caret Square O Right",
  "la-caret-square-o-up": "Caret Square O Up",
  "la-caret-up": "Caret Up",
  "la-cart-arrow-down": "Cart Arrow Down",
  "la-cart-plus": "Cart Plus",
  "la-cc": "Cc",
  "la-cc-amex": "Cc Amex",
  "la-cc-diners-club": "Cc Diners Club",
  "la-cc-discover": "Cc Discover",
  "la-cc-jcb": "Cc Jcb",
  "la-cc-mastercard": "Cc Mastercard",
  "la-cc-paypal": "Cc Paypal",
  "la-cc-stripe": "Cc Stripe",
  "la-cc-visa": "Cc Visa",
  "la-certificate": "Certificate",
  "la-chain": "Chain",
  "la-chain-broken": "Chain Broken",
  "la-check": "Check",
  "la-check-circle": "Check Circle",
  "la-check-circle-o": "Check Circle O",
  "la-check-square": "Check Square",
  "la-check-square-o": "Check Square O",
  "la-chevron-circle-down": "Chevron Circle Down",
  "la-chevron-circle-left": "Chevron Circle Left",
  "la-chevron-circle-right": "Chevron Circle Right",
  "la-chevron-circle-up": "Chevron Circle Up",
  "la-chevron-down": "Chevron Down",
  "la-chevron-left": "Chevron Left",
  "la-chevron-right": "Chevron Right",
  "la-chevron-up": "Chevron Up",
  "la-child": "Child",
  "la-chrome": "Chrome",
  "la-circle": "Circle",
  "la-circle-o": "Circle O",
  "la-circle-o-notch": "Circle O Notch",
  "la-circle-thin": "Circle Thin",
  "la-clipboard": "Clipboard",
  "la-clock-o": "Clock O",
  "la-clone": "Clone",
  "la-close": "Close",
  "la-cloud": "Cloud",
  "la-cloud-download": "Cloud Download",
  "la-cloud-upload": "Cloud Upload",
  "la-cny": "Cny",
  "la-code": "Code",
  "la-code-fork": "Code Fork",
  "la-codepen": "Codepen",
  "la-codiepie": "Codiepie",
  "la-coffee": "Coffee",
  "la-cog": "Cog",
  "la-cogs": "Cogs",
  "la-columns": "Columns",
  "la-comment": "Comment",
  "la-comment-o": "Comment O",
  "la-commenting": "Commenting",
  "la-commenting-o": "Commenting O",
  "la-comments": "Comments",
  "la-comments-o": "Comments O",
  "la-compass": "Compass",
  "la-compress": "Compress",
  "la-connectdevelop": "Connectdevelop",
  "la-contao": "Contao",
  "la-copy": "Copy",
  "la-copyright": "Copyright",
  "la-creative-commons": "Creative Commons",
  "la-credit-card": "Credit Card",
  "la-credit-card-alt": "Credit Card Alt",
  "la-crop": "Crop",
  "la-crosshairs": "Crosshairs",
  "la-css3": "Css3",
  "la-cube": "Cube",
  "la-cubes": "Cubes",
  "la-cut": "Cut",
  "la-cutlery": "Cutlery",
  "la-dashboard": "Dashboard",
  "la-dashcube": "Dashcube",
  "la-database": "Database",
  "la-dedent": "Dedent",
  "la-delicious": "Delicious",
  "la-desktop": "Desktop",
  "la-deviantart": "Deviantart",
  "la-diamond": "Diamond",
  "la-digg": "Digg",
  "la-dollar": "Dollar",
  "la-dot-circle-o": "Dot Circle O",
  "la-download": "Download",
  "la-dribbble": "Dribbble",
  "la-dropbox": "Dropbox",
  "la-drupal": "Drupal",
  "la-edge": "Edge",
  "la-edit": "Edit",
  "la-eject": "Eject",
  "la-ellipsis-h": "Ellipsis H",
  "la-ellipsis-v": "Ellipsis V",
  "la-empire": "Empire",
  "la-envelope": "Envelope",
  "la-envelope-o": "Envelope O",
  "la-envelope-square": "Envelope Square",
  "la-eraser": "Eraser",
  "la-eur": "Eur",
  "la-euro": "Euro",
  "la-exchange": "Exchange",
  "la-exclamation": "Exclamation",
  "la-exclamation-circle": "Exclamation Circle",
  "la-exclamation-triangle": "Exclamation Triangle",
  "la-expand": "Expand",
  "la-expeditedssl": "Expeditedssl",
  "la-external-link": "External Link",
  "la-external-link-square": "External Link Square",
  "la-eye": "Eye",
  "la-eye-slash": "Eye Slash",
  "la-eyedropper": "Eyedropper",
  "la-facebook": "Facebook",
  "la-facebook-f": "Facebook F",
  "la-facebook-official": "Facebook Official",
  "la-facebook-square": "Facebook Square",
  "la-fast-backward": "Fast Backward",
  "la-fast-forward": "Fast Forward",
  "la-fax": "Fax",
  "la-feed": "Feed",
  "la-female": "Female",
  "la-fighter-jet": "Fighter Jet",
  "la-file": "File",
  "la-file-archive-o": "File Archive O",
  "la-file-audio-o": "File Audio O",
  "la-file-code-o": "File Code O",
  "la-file-excel-o": "File Excel O",
  "la-file-image-o": "File Image O",
  "la-file-movie-o": "File Movie O",
  "la-file-o": "File O",
  "la-file-pdf-o": "File Pdf O",
  "la-file-photo-o": "File Photo O",
  "la-file-picture-o": "File Picture O",
  "la-file-powerpoint-o": "File Powerpoint O",
  "la-file-sound-o": "File Sound O",
  "la-file-text": "File Text",
  "la-file-text-o": "File Text O",
  "la-file-video-o": "File Video O",
  "la-file-word-o": "File Word O",
  "la-file-zip-o": "File Zip O",
  "la-files-o": "Files O",
  "la-film": "Film",
  "la-filter": "Filter",
  "la-fire": "Fire",
  "la-fire-extinguisher": "Fire Extinguisher",
  "la-firefox": "Firefox",
  "la-flag": "Flag",
  "la-flag-checkered": "Flag Checkered",
  "la-flag-o": "Flag O",
  "la-flash": "Flash",
  "la-flask": "Flask",
  "la-flickr": "Flickr",
  "la-floppy-o": "Floppy O",
  "la-folder": "Folder",
  "la-folder-o": "Folder O",
  "la-folder-open": "Folder Open",
  "la-folder-open-o": "Folder Open O",
  "la-font": "Font",
  "la-fonticons": "Fonticons",
  "la-fort-awesome": "Fort Awesome",
  "la-forumbee": "Forumbee",
  "la-forward": "Forward",
  "la-foursquare": "Foursquare",
  "la-frown-o": "Frown O",
  "la-futbol-o": "Futbol O",
  "la-gamepad": "Gamepad",
  "la-gavel": "Gavel",
  "la-gbp": "Gbp",
  "la-ge": "Ge",
  "la-gear": "Gear",
  "la-gears": "Gears",
  "la-genderless": "Genderless",
  "la-get-pocket": "Get Pocket",
  "la-gg": "Gg",
  "la-gg-circle": "Gg Circle",
  "la-gift": "Gift",
  "la-git": "Git",
  "la-git-square": "Git Square",
  "la-github": "Github",
  "la-github-alt": "Github Alt",
  "la-github-square": "Github Square",
  "la-gittip": "Gittip",
  "la-glass": "Glass",
  "la-globe": "Globe",
  "la-google": "Google",
  "la-google-plus": "Google Plus",
  "la-google-plus-square": "Google Plus Square",
  "la-google-wallet": "Google Wallet",
  "la-graduation-cap": "Graduation Cap",
  "la-gratipay": "Gratipay",
  "la-group": "Group",
  "la-h-square": "H Square",
  "la-hacker-news": "Hacker News",
  "la-hand-grab-o": "Hand Grab O",
  "la-hand-lizard-o": "Hand Lizard O",
  "la-hand-o-down": "Hand O Down",
  "la-hand-o-left": "Hand O Left",
  "la-hand-o-right": "Hand O Right",
  "la-hand-o-up": "Hand O Up",
  "la-hand-paper-o": "Hand Paper O",
  "la-hand-peace-o": "Hand Peace O",
  "la-hand-pointer-o": "Hand Pointer O",
  "la-hand-rock-o": "Hand Rock O",
  "la-hand-scissors-o": "Hand Scissors O",
  "la-hand-spock-o": "Hand Spock O",
  "la-hand-stop-o": "Hand Stop O",
  "la-hashtag": "Hashtag",
  "la-hdd-o": "Hdd O",
  "la-header": "Header",
  "la-headphones": "Headphones",
  "la-heart": "Heart",
  "la-heart-o": "Heart O",
  "la-heartbeat": "Heartbeat",
  "la-history": "History",
  "la-home": "Home",
  "la-hospital-o": "Hospital O",
  "la-hotel": "Hotel",
  "la-hourglass": "Hourglass",
  "la-hourglass-1": "Hourglass 1",
  "la-hourglass-2": "Hourglass 2",
  "la-hourglass-3": "Hourglass 3",
  "la-hourglass-end": "Hourglass End",
  "la-hourglass-half": "Hourglass Half",
  "la-hourglass-o": "Hourglass O",
  "la-hourglass-start": "Hourglass Start",
  "la-houzz": "Houzz",
  "la-html5": "Html5",
  "la-i-cursor": "I Cursor",
  "la-ils": "Ils",
  "la-image": "Image",
  "la-inbox": "Inbox",
  "la-indent": "Indent",
  "la-industry": "Industry",
  "la-info": "Info",
  "la-info-circle": "Info Circle",
  "la-inr": "Inr",
  "la-instagram": "Instagram",
  "la-institution": "Institution",
  "la-internet-explorer": "Internet Explorer",
  "la-intersex": "Intersex",
  "la-ioxhost": "Ioxhost",
  "la-italic": "Italic",
  "la-joomla": "Joomla",
  "la-jpy": "Jpy",
  "la-jsfiddle": "Jsfiddle",
  "la-key": "Key",
  "la-keyboard-o": "Keyboard O",
  "la-krw": "Krw",
  "la-language": "Language",
  "la-laptop": "Laptop",
  "la-lastfm": "Lastfm",
  "la-lastfm-square": "Lastfm Square",
  "la-leaf": "Leaf",
  "la-leanpub": "Leanpub",
  "la-legal": "Legal",
  "la-lemon-o": "Lemon O",
  "la-level-down": "Level Down",
  "la-level-up": "Level Up",
  "la-life-bouy": "Life Bouy",
  "la-life-buoy": "Life Buoy",
  "la-life-ring": "Life Ring",
  "la-life-saver": "Life Saver",
  "la-lightbulb-o": "Lightbulb O",
  "la-line-chart": "Line Chart",
  "la-link": "Link",
  "la-linkedin": "Linkedin",
  "la-linkedin-square": "Linkedin Square",
  "la-linux": "Linux",
  "la-list": "List",
  "la-list-alt": "List Alt",
  "la-list-ol": "List Ol",
  "la-list-ul": "List Ul",
  "la-location-arrow": "Location Arrow",
  "la-lock": "Lock",
  "la-long-arrow-down": "Long Arrow Down",
  "la-long-arrow-left": "Long Arrow Left",
  "la-long-arrow-right": "Long Arrow Right",
  "la-long-arrow-up": "Long Arrow Up",
  "la-magic": "Magic",
  "la-magnet": "Magnet",
  "la-mail-forward": "Mail Forward",
  "la-mail-reply": "Mail Reply",
  "la-mail-reply-all": "Mail Reply All",
  "la-male": "Male",
  "la-map": "Map",
  "la-map-marker": "Map Marker",
  "la-map-o": "Map O",
  "la-map-pin": "Map Pin",
  "la-map-signs": "Map Signs",
  "la-mars": "Mars",
  "la-mars-double": "Mars Double",
  "la-mars-stroke": "Mars Stroke",
  "la-mars-stroke-h": "Mars Stroke H",
  "la-mars-stroke-v": "Mars Stroke V",
  "la-maxcdn": "Maxcdn",
  "la-meanpath": "Meanpath",
  "la-medium": "Medium",
  "la-medkit": "Medkit",
  "la-meh-o": "Meh O",
  "la-mercury": "Mercury",
  "la-microphone": "Microphone",
  "la-microphone-slash": "Microphone Slash",
  "la-minus": "Minus",
  "la-minus-circle": "Minus Circle",
  "la-minus-square": "Minus Square",
  "la-minus-square-o": "Minus Square O",
  "la-mixcloud": "Mixcloud",
  "la-mobile": "Mobile",
  "la-mobile-phone": "Mobile Phone",
  "la-modx": "Modx",
  "la-money": "Money",
  "la-moon-o": "Moon O",
  "la-mortar-board": "Mortar Board",
  "la-motorcycle": "Motorcycle",
  "la-mouse-pointer": "Mouse Pointer",
  "la-music": "Music",
  "la-navicon": "Navicon",
  "la-neuter": "Neuter",
  "la-newspaper-o": "Newspaper O",
  "la-object-group": "Object Group",
  "la-object-ungroup": "Object Ungroup",
  "la-odnoklassniki": "Odnoklassniki",
  "la-odnoklassniki-square": "Odnoklassniki Square",
  "la-opencart": "Opencart",
  "la-openid": "Openid",
  "la-opera": "Opera",
  "la-optin-monster": "Optin Monster",
  "la-outdent": "Outdent",
  "la-pagelines": "Pagelines",
  "la-paint-brush": "Paint Brush",
  "la-paper-plane": "Paper Plane",
  "la-paper-plane-o": "Paper Plane O",
  "la-paperclip": "Paperclip",
  "la-paragraph": "Paragraph",
  "la-paste": "Paste",
  "la-pause": "Pause",
  "la-pause-circle": "Pause Circle",
  "la-pause-circle-o": "Pause Circle O",
  "la-paw": "Paw",
  "la-paypal": "Paypal",
  "la-pencil": "Pencil",
  "la-pencil-square": "Pencil Square",
  "la-pencil-square-o": "Pencil Square O",
  "la-percent": "Percent",
  "la-phone": "Phone",
  "la-phone-square": "Phone Square",
  "la-photo": "Photo",
  "la-picture-o": "Picture O",
  "la-pie-chart": "Pie Chart",
  "la-pied-piper": "Pied Piper",
  "la-pied-piper-alt": "Pied Piper Alt",
  "la-pinterest": "Pinterest",
  "la-pinterest-p": "Pinterest P",
  "la-pinterest-square": "Pinterest Square",
  "la-plane": "Plane",
  "la-play": "Play",
  "la-play-circle": "Play Circle",
  "la-play-circle-o": "Play Circle O",
  "la-plug": "Plug",
  "la-plus": "Plus",
  "la-plus-circle": "Plus Circle",
  "la-plus-square": "Plus Square",
  "la-plus-square-o": "Plus Square O",
  "la-power-off": "Power Off",
  "la-print": "Print",
  "la-product-hunt": "Product Hunt",
  "la-puzzle-piece": "Puzzle Piece",
  "la-qq": "Qq",
  "la-qrcode": "Qrcode",
  "la-question": "Question",
  "la-question-circle": "Question Circle",
  "la-quote-left": "Quote Left",
  "la-quote-right": "Quote Right",
  "la-ra": "Ra",
  "la-random": "Random",
  "lab la-readme": "Read Me",
  "la-rebel": "Rebel",
  "la-recycle": "Recycle",
  "la-reddit": "Reddit",
  "la-reddit-alien": "Reddit Alien",
  "la-reddit-square": "Reddit Square",
  "la-refresh": "Refresh",
  "la-registered": "Registered",
  "la-remove": "Remove",
  "la-renren": "Renren",
  "la-reorder": "Reorder",
  "la-repeat": "Repeat",
  "la-reply": "Reply",
  "la-reply-all": "Reply All",
  "la-retweet": "Retweet",
  "la-rmb": "Rmb",
  "la-road": "Road",
  "la-rocket": "Rocket",
  "la-rotate-left": "Rotate Left",
  "la-rotate-right": "Rotate Right",
  "la-rouble": "Rouble",
  "la-rss": "Rss",
  "la-rss-square": "Rss Square",
  "la-rub": "Rub",
  "la-ruble": "Ruble",
  "la-rupee": "Rupee",
  "la-safari": "Safari",
  "la-save": "Save",
  "la-scissors": "Scissors",
  "la-scribd": "Scribd",
  "la-search": "Search",
  "la-search-minus": "Search Minus",
  "la-search-plus": "Search Plus",
  "la-sellsy": "Sellsy",
  "la-send": "Send",
  "la-send-o": "Send O",
  "la-server": "Server",
  "la-share": "Share",
  "la-share-alt": "Share Alt",
  "la-share-alt-square": "Share Alt Square",
  "la-share-square": "Share Square",
  "la-share-square-o": "Share Square O",
  "la-shekel": "Shekel",
  "la-sheqel": "Sheqel",
  "la-shield": "Shield",
  "la-ship": "Ship",
  "la-shirtsinbulk": "Shirtsinbulk",
  "la-shopping-bag": "Shopping Bag",
  "la-shopping-basket": "Shopping Basket",
  "la-shopping-cart": "Shopping Cart",
  "la-sign-in": "Sign In",
  "la-sign-out": "Sign Out",
  "la-signal": "Signal",
  "la-simplybuilt": "Simplybuilt",
  "la-sitemap": "Sitemap",
  "la-skyatlas": "Skyatlas",
  "la-skype": "Skype",
  "la-slack": "Slack",
  "la-sliders": "Sliders",
  "la-slideshare": "Slideshare",
  "la-smile-o": "Smile O",
  "la-soccer-ball-o": "Soccer Ball O",
  "la-sort": "Sort",
  "la-sort-alpha-asc": "Sort Alpha Asc",
  "la-sort-alpha-desc": "Sort Alpha Desc",
  "la-sort-amount-asc": "Sort Amount Asc",
  "la-sort-amount-desc": "Sort Amount Desc",
  "la-sort-asc": "Sort Asc",
  "la-sort-desc": "Sort Desc",
  "la-sort-down": "Sort Down",
  "la-sort-numeric-asc": "Sort Numeric Asc",
  "la-sort-numeric-desc": "Sort Numeric Desc",
  "la-sort-up": "Sort Up",
  "la-soundcloud": "Soundcloud",
  "la-space-shuttle": "Space Shuttle",
  "la-spinner": "Spinner",
  "la-spoon": "Spoon",
  "la-spotify": "Spotify",
  "la-square": "Square",
  "la-square-o": "Square O",
  "la-stack-exchange": "Stack Exchange",
  "la-stack-overflow": "Stack Overflow",
  "la-star": "Star",
  "la-star-half": "Star Half",
  "la-star-half-empty": "Star Half Empty",
  "la-star-half-full": "Star Half Full",
  "la-star-half-o": "Star Half O",
  "la-star-o": "Star O",
  "la-steam": "Steam",
  "la-steam-square": "Steam Square",
  "la-step-backward": "Step Backward",
  "la-step-forward": "Step Forward",
  "la-stethoscope": "Stethoscope",
  "la-sticky-note": "Sticky Note",
  "la-sticky-note-o": "Sticky Note O",
  "la-stop": "Stop",
  "la-stop-circle": "Stop Circle",
  "la-stop-circle-o": "Stop Circle O",
  "la-street-view": "Street View",
  "la-strikethrough": "Strikethrough",
  "la-stumbleupon": "Stumbleupon",
  "la-stumbleupon-circle": "Stumbleupon Circle",
  "la-subscript": "Subscript",
  "la-subway": "Subway",
  "la-suitcase": "Suitcase",
  "la-sun-o": "Sun O",
  "la-superscript": "Superscript",
  "la-support": "Support",
  "la-table": "Table",
  "la-tablet": "Tablet",
  "la-tachometer": "Tachometer",
  "la-tag": "Tag",
  "la-tags": "Tags",
  "la-tasks": "Tasks",
  "la-taxi": "Taxi",
  "la-television": "Television",
  "la-tencent-weibo": "Tencent Weibo",
  "la-terminal": "Terminal",
  "la-text-height": "Text Height",
  "la-text-width": "Text Width",
  "la-th": "Th",
  "la-th-large": "Th Large",
  "la-th-list": "Th List",
  "la-thumb-tack": "Thumb Tack",
  "la-thumbs-down": "Thumbs Down",
  "la-thumbs-o-down": "Thumbs O Down",
  "la-thumbs-o-up": "Thumbs O Up",
  "la-thumbs-up": "Thumbs Up",
  "la-ticket": "Ticket",
  "la-times": "Times",
  "la-times-circle": "Times Circle",
  "la-times-circle-o": "Times Circle O",
  "la-tint": "Tint",
  "la-toggle-down": "Toggle Down",
  "la-toggle-left": "Toggle Left",
  "la-toggle-off": "Toggle Off",
  "la-toggle-on": "Toggle On",
  "la-toggle-right": "Toggle Right",
  "la-toggle-up": "Toggle Up",
  "la-trademark": "Trademark",
  "la-train": "Train",
  "la-transgender": "Transgender",
  "la-transgender-alt": "Transgender Alt",
  "la-trash": "Trash",
  "la-trash-o": "Trash O",
  "la-tree": "Tree",
  "la-trello": "Trello",
  "la-tripadvisor": "Tripadvisor",
  "la-trophy": "Trophy",
  "la-truck": "Truck",
  "la-try": "Try",
  "la-tty": "Tty",
  "la-tumblr": "Tumblr",
  "la-tumblr-square": "Tumblr Square",
  "la-turkish-lira": "Turkish Lira",
  "la-tv": "Tv",
  "la-twitch": "Twitch",
  "la-twitter": "Twitter",
  "la-twitter-square": "Twitter Square",
  "la-umbrella": "Umbrella",
  "la-underline": "Underline",
  "la-undo": "Undo",
  "la-university": "University",
  "la-unlink": "Unlink",
  "la-unlock": "Unlock",
  "la-unlock-alt": "Unlock Alt",
  "la-unsorted": "Unsorted",
  "la-upload": "Upload",
  "la-usb": "Usb",
  "la-usd": "Usd",
  "la-user": "User",
  "la-user-md": "User Md",
  "la-user-plus": "User Plus",
  "la-user-secret": "User Secret",
  "la-user-times": "User Times",
  "la-users": "Users",
  "la-venus": "Venus",
  "la-venus-double": "Venus Double",
  "la-venus-mars": "Venus Mars",
  "la-viacoin": "Viacoin",
  "la-video-camera": "Video Camera",
  "la-vimeo": "Vimeo",
  "la-vimeo-square": "Vimeo Square",
  "la-vine": "Vine",
  "la-vk": "Vk",
  "la-volume-down": "Volume Down",
  "la-volume-off": "Volume Off",
  "la-volume-up": "Volume Up",
  "la-warning": "Warning",
  "la-wechat": "Wechat",
  "la-weibo": "Weibo",
  "la-weixin": "Weixin",
  "la-whatsapp": "Whatsapp",
  "la-wheelchair": "Wheelchair",
  "la-wifi": "Wifi",
  "la-wikipedia-w": "Wikipedia W",
  "la-windows": "Windows",
  "la-won": "Won",
  "la-wordpress": "Wordpress",
  "la-wrench": "Wrench",
  "la-xing": "Xing",
  "la-xing-square": "Xing Square",
  "la-y-combinator": "Y Combinator",
  "la-y-combinator-square": "Y Combinator Square",
  "la-yahoo": "Yahoo",
  "la-yc": "Yc",
  "la-yc-square": "Yc Square",
  "la-yelp": "Yelp",
  "la-yen": "Yen",
  "la-youtube": "Youtube",
  "la-youtube-play": "Youtube Play",
  "la-youtube-square": "Youtube Square"
}